library(ggplot2)
library(markovchain)
library(data.table)
library(stringr)
rm(list=ls())
test=read.csv("test.csv",stringsAsFactors = F)
test<- as.data.table(test)
source("temp.R")
crt.result=t(sapply(test[, Sequence],crt.predict))